### Checkout cart
POST http://localhost:8080/api/v1/cart/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkQXQiOjE3MTk3MzU1NTEsInVzZXJJRCI6IjEifQ.7AYTJ6uDrLZYh1eWvLBoXOONm-L-5XagFKne93zNI_U

{
    "items": [
        {
            "productID": 1,
            "quantity": 6
        }
    ]    
}