### get all products
GET  http://localhost:8080/api/v1/products


### get one product by id
GET http://localhost:8080/api/v1/products/1


### create product
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "name": "T-Shirt",
    "description": "Balengacia t-shirt",
    "image": "image.png",
    "price": 4500,
    "quantity": 23
}


### Update product
PUT http://localhost:8080/api/v1/products/1
Content-Type: application/json

{
    "name": "T-Shirt 42",
    "description": "Balengacia T-shirt",
    "image": "updated.png",
    "price": 4550,
    "quantity": 21
}

